# import numpy as np
# Calculate the total revenue generated by two product categories in a store.

# category1_revenue = np.array([500,600,700,550])
# category2_revenue = np.array([450,700,800,600])

# revenue = category1_revenue+category2_revenue
# print(f"Revenue: {revenue}")

# ---------------------------------------------------------------------------

# 2. calculate the  profit made
# revenue = np.array([10000,12000,11000,10500])
# expenses = np.array([4000,5000,4500,4800])

# profit = revenue-expenses
# print(f"Profit: {profit}")

# ---------------------------------------------------------------------------

# 3. products in a store that are out of stock(quantity = 0)

# arr = np.array([10,0,5,0,20,0])
# stock = np.where(arr==0)
# print(f"Out of Stocks are : {stock}")

# ---------------------------------------------------------------------------

# 4. calculate the total cost of items in a shopping cart , considering the quantity and price per item.

# quantity = np.array([2,3,4,1])
# price_per_item = np.array([10.0,5.0,8.0,12.0])
# cost = []
# for p in range(len(price_per_item)):
#     cost.append(quantity[p]*price_per_item[p])

# print(f"Cost of all the Products: {cost}")

# Easy approach
# print(f"Cost of all the Products: {quantity*price_per_item}")


# ---------------------------------------------------------------------------
